### ISSUE TITLE
BTAPResults: Costing JSON reorg. 

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#254] opened 2019-09-27 19:35 UTC
### Description
Currently the costing JSON tree is inconsistent. This causes difficulty when using Tableau, PowerBI and Python.  This task is to flatten the data structure to consist of a top level that will have building wide information or single data, and one level below which will contain table-row (array) data. 
Below is a sample but use your judgement on how it should be put together. Ideally, data would  be organized by space/zone/air_loop/plant_loop tables. 
Tables will not have totals or average rows.. that data should be kept on the top level if needed. 

```json
{
  "rs_means_city": "PRINCE GEORGE",
  "rs_means_prov": "BRITISH COLUMBIA",
  "surface_opaque_table":[],
  "surface_fenestration_table":[],
  "space_table":[], // This will include space level costs (lighting for example)...items here should be summed up in the thermal zone table.
  "thermal_zone_table":[], // This will include thermal zone level costs if any must include multipliers.
  "thermal_zone_equipment":[], // this will include zone equipment costs. baseboards, PTACs, etc. Must have name of themal zone
  "air_loop_table":[], // This will include all ductwork and other items that make up the airloop. index by system name.
  "air_loop_equipment":[], // This will include all the airloop equipment, unit costs, multipliers and totals.
  "plant_loop_table":[], // this will include all plant loop information and costing (pipe length, cost, etc)
  "plant_loop_equipment_table":[], // this will include plant loop cost items (of type Pumps, boilers, chilllers, etc, blanks are okay. Should use OS object name suffix as type. )
  "coil_table":[], // this will include all coils.. not sure if this is a plant or zone item.. so keeping it here? If so zone/loop name should be. blanks are ok
  "fan_table":[], //We currently only have a supply fan for each air loop.. should this be broken out for when we have more fans in a loop or elsewhere?
  "costing_envelope_cost": 377239.91,
  "costing_lighting_cost": 377239.91,
  "costing_hvac_cost": 377239.91,
  "costing_shw_cost": 377239.91
}
```

### Approach
Create a new_costing hash so we can have the old and new output format can be used concurrently until everything is tested and ready to go. 

### Repositories Involved
https://github.com/NREL/openstudio-standards/tree/nrcan

25.001	|Cold climate heat pumps for space and hot water heating	|Jeremy Sager

**Comment by phylroy** [comment] 2019-10-28 02:46
Hey Jeff, 

Search for "pl_comments" below. 

```json
{
  "pl_comments": " Why not just append this information to an airloop table?",
  "air_loop_table": [
    {
      "sys_type": 6,
      "name": "Sys_6_VAV with Reheat",
      "airloop_flow_m3_per_s": 4.639308452606201,
      "num_rooftop_units": 1,
      "ahu_counter": 1,
      "ahu_l_per_s": 6000,
      "base_ahu_cost": 76557.43,
      "revised_base_ahu_cost": 59195.59,
      "pl_comment": "is there always only one hrv in an airloop? If so, promote this information up. ",
      "hrv": {
        "hrv_type": "HeatExchanger_AirToAir_SensibleAndLatent",
        "hrv_name": "Sys_6_VAV with Reheat ERV",
        "hrv_size_m3ps": 0.7,
        "hrv_return_fan_size_m3ps": 0.0,
        "hrv_cost": 10020.06,
        "revised_hrv_cost": 7016.34
      },
      "pl_comment": "It may be a good idea to create a coils table with the coil information, include air_loop it is being used in. A starter table could be found in the E+ sql coil data table.",
      "equipment_info": [
        {
          "eq_category": "Coil_Cooling_Water",
          "heating_fuel": "none",
          "cooling_type": "CHW",
          "capacity_kw": 83.013,
          "cost": 20501.07
        },
        {
          "eq_category": "Coil_Heating_Electric",
          "heating_fuel": "elec",
          "cooling_type": "none",
          "capacity_kw": 30.254,
          "cost": 9361.69
        }
      ],
      "pl_comment": "It may be a good idea to create a terminal vav table, include air_loop it is being used  as well as the zone. the unit_info can be brought up. ",
      "reheat_recool": [
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 5",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.945,
            "pipe_dist_m": 22.8,
            "elect_dist_m": 22.8,
            "num_units": 1
          },
          "cost": 3558.77
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 1",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 1.427,
            "pipe_dist_m": 0.0,
            "elect_dist_m": 0.0,
            "num_units": 1
          },
          "cost": 777.9
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 2",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.904,
            "pipe_dist_m": 14.4,
            "elect_dist_m": 14.4,
            "num_units": 1
          },
          "cost": 4843.03
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 3",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.892,
            "pipe_dist_m": 22.8,
            "elect_dist_m": 22.8,
            "num_units": 1
          },
          "cost": 5900.79
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 4",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.472,
            "pipe_dist_m": 14.4,
            "elect_dist_m": 14.4,
            "num_units": 1
          },
          "cost": 4333.52
        }
      ]
    },
    {
      "sys_type": 6,
      "name": "Sys_6_VAV with Reheat 1",
      "airloop_flow_m3_per_s": 4.79355001449585,
      "num_rooftop_units": 1,
      "ahu_counter": 1,
      "ahu_l_per_s": 6000,
      "base_ahu_cost": 76557.43,
      "revised_base_ahu_cost": 61163.65,
      "hrv": {
        "hrv_type": "HeatExchanger_AirToAir_SensibleAndLatent",
        "hrv_name": "Sys_6_VAV with Reheat 1 ERV",
        "hrv_size_m3ps": 0.7,
        "hrv_return_fan_size_m3ps": 0.0,
        "hrv_cost": 10020.06,
        "revised_hrv_cost": 7016.34
      },
      "equipment_info": [
        {
          "eq_category": "Coil_Cooling_Water",
          "heating_fuel": "none",
          "cooling_type": "CHW",
          "capacity_kw": 85.52,
          "cost": 20501.07
        },
        {
          "eq_category": "Coil_Heating_Electric",
          "heating_fuel": "elec",
          "cooling_type": "none",
          "capacity_kw": 29.767,
          "cost": 9361.69
        }
      ],
      "reheat_recool": [
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 6",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 1.71,
            "pipe_dist_m": 0.0,
            "elect_dist_m": 0.0,
            "num_units": 1
          },
          "cost": 777.9
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 9",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.532,
            "pipe_dist_m": 14.4,
            "elect_dist_m": 14.4,
            "num_units": 1
          },
          "cost": 4641.02
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 8",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.819,
            "pipe_dist_m": 22.8,
            "elect_dist_m": 22.8,
            "num_units": 1
          },
          "cost": 5900.79
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 7",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.868,
            "pipe_dist_m": 14.4,
            "elect_dist_m": 14.4,
            "num_units": 1
          },
          "cost": 4843.03
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 10",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.864,
            "pipe_dist_m": 22.8,
            "elect_dist_m": 22.8,
            "num_units": 1
          },
          "cost": 5900.81
        }
      ]
    },
    {
      "sys_type": 6,
      "name": "Sys_6_VAV with Reheat 2",
      "airloop_flow_m3_per_s": 5.045681953430176,
      "num_rooftop_units": 1,
      "ahu_counter": 1,
      "ahu_l_per_s": 6000,
      "base_ahu_cost": 98896.03,
      "revised_base_ahu_cost": 83166.32,
      "hrv": {
        "hrv_type": "HeatExchanger_AirToAir_SensibleAndLatent",
        "hrv_name": "Sys_6_VAV with Reheat 2 ERV",
        "hrv_size_m3ps": 0.7,
        "hrv_return_fan_size_m3ps": 0.0,
        "hrv_cost": 10020.06,
        "revised_hrv_cost": 7016.34
      },
      "equipment_info": [
        {
          "eq_category": "Coil_Cooling_Water",
          "heating_fuel": "none",
          "cooling_type": "CHW",
          "capacity_kw": 89.436,
          "cost": 20501.07
        },
        {
          "eq_category": "Coil_Heating_Electric",
          "heating_fuel": "elec",
          "cooling_type": "none",
          "capacity_kw": 28.972,
          "cost": 9361.69
        }
      ],
      "reheat_recool": [
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 13",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.821,
            "pipe_dist_m": 22.8,
            "elect_dist_m": 22.8,
            "num_units": 1
          },
          "cost": 5900.79
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 15",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.891,
            "pipe_dist_m": 22.8,
            "elect_dist_m": 22.8,
            "num_units": 1
          },
          "cost": 5900.81
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 11",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 1.85,
            "pipe_dist_m": 0.0,
            "elect_dist_m": 0.0,
            "num_units": 1
          },
          "cost": 777.9
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 12",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.891,
            "pipe_dist_m": 14.4,
            "elect_dist_m": 14.4,
            "num_units": 1
          },
          "cost": 4843.03
        },
        {
          "terminal": "AirTerminal_SingleDuct_VAV_Reheat",
          "zone_mult": 1.0,
          "box_type": "VAVFanMixingBoxesHtg",
          "box_name": "Air Terminal Single Duct VAV Reheat 14",
          "unit_info": {
            "size_kw": 0.0,
            "air_flow_m3_per_s": 0.593,
            "pipe_dist_m": 14.4,
            "elect_dist_m": 14.4,
            "num_units": 1
          },
          "cost": 4641.02
        }
      ]
    }
  ],


  "pl_comments": "Is this for the building? does teh HW line mean for the coils and basebords? If so.. why is this not broken down by floor like the ducts?",
  "mech_to_roof": {
    "Gas_Line_m": 0.0,
    "HW_Line_m": 0.0,
    "CHW_Line_m": 274.9,
    "Elec_Line_m": 137.4,
    "Total_cost": 17438.53
  },

  "pl_comments": "Could we have all the ductwork in the same table. The trunk_duct (singluar) could be brought in to table as below..I'm guessing it does not have a floor because this is independant of the floors.  Does the `numer_of_runs` mean supply and return combined.. if so could it be explicitly defined as such?",
  "pl_comments": "How is hw_piping handled in for example hydronic baseboards?",

  "trunk_ducts": [
    [
      {
        "Floor": "Misc?",
        "SupplyDuctSize_in": 36.0,
        "SupplyDuctLength_m": 9.1,
        "ReturnDuctSize_in": 36.0,
        "ReturnDuctLength_m": 9.1,
        "TotalDuctCost": 4691.7
      },
      {
        "Floor": "Building Story 1",
        "Predominant_space_type": "Office open plan",
        "SupplyDuctSize_in": 35.88,
        "SupplyDuctLength_m": 56.4,
        "ReturnDuctSize_in": 35.88,
        "ReturnDuctLength_m": 56.4,
        "TotalDuctCost": 28920.24,
        "Multiplier": 1.0
      },
      {
        "Floor": "Building Story 2",
        "Predominant_space_type": "Office open plan",
        "SupplyDuctSize_in": 36.47,
        "SupplyDuctLength_m": 56.4,
        "ReturnDuctSize_in": 36.47,
        "ReturnDuctLength_m": 56.4,
        "TotalDuctCost": 28920.24,
        "Multiplier": 1.0
      },
      {
        "Floor": "Building Story 3",
        "Predominant_space_type": "Office open plan",
        "SupplyDuctSize_in": 37.42,
        "SupplyDuctLength_m": 56.4,
        "ReturnDuctSize_in": 37.42,
        "ReturnDuctLength_m": 56.4,
        "TotalDuctCost": 28920.24,
        "Multiplier": 1.0
      }
    ]
  ],

  "pl_comments": "This could be in the thermal zone table with the building story as a column in that table?",
  "tz_distribution": [
    [
      {
        "Story": "Building Story 1",
        "thermal_zones": [
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.945,
            "num_diff": 8,
            "ducting_lbs": 320,
            "duct_insulation_ft2": 200,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 80,
            "cost": 4561.1
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.945,
            "num_diff": 8,
            "ducting_lbs": 320,
            "duct_insulation_ft2": 200,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 80,
            "cost": 4561.1
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 1",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 1.427,
            "num_diff": 12,
            "ducting_lbs": 480,
            "duct_insulation_ft2": 300,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 120,
            "cost": 6841.65
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 1",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 1.427,
            "num_diff": 12,
            "ducting_lbs": 480,
            "duct_insulation_ft2": 300,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 120,
            "cost": 6841.65
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 2",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.904,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 2",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.904,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 3",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.892,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 3",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.892,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 4",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.472,
            "num_diff": 5,
            "ducting_lbs": 290,
            "duct_insulation_ft2": 224,
            "flex_duct_sz_in": 6,
            "flex_duct_length_ft": 40,
            "cost": 3222.09
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 1_SCH=A 4",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.472,
            "num_diff": 5,
            "ducting_lbs": 290,
            "duct_insulation_ft2": 224,
            "flex_duct_sz_in": 6,
            "flex_duct_length_ft": 40,
            "cost": 3222.09
          }
        ]
      },
      {
        "Story": "Building Story 2",
        "thermal_zones": [
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 1.71,
            "num_diff": 14,
            "ducting_lbs": 560,
            "duct_insulation_ft2": 350,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 140,
            "cost": 7981.92
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 1.71,
            "num_diff": 14,
            "ducting_lbs": 560,
            "duct_insulation_ft2": 350,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 140,
            "cost": 7981.92
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 1",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.532,
            "num_diff": 6,
            "ducting_lbs": 395,
            "duct_insulation_ft2": 306,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 48,
            "cost": 4469.57
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 1",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.532,
            "num_diff": 6,
            "ducting_lbs": 395,
            "duct_insulation_ft2": 306,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 48,
            "cost": 4469.57
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 2",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.819,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 2",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.819,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 3",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.868,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 3",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.868,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 4",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.864,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 2_SCH=A 4",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.864,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          }
        ]
      },
      {
        "Story": "Building Story 3",
        "thermal_zones": [
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.821,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.821,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 1",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.891,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 1",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.891,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 2",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 1.85,
            "num_diff": 15,
            "ducting_lbs": 600,
            "duct_insulation_ft2": 375,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 150,
            "cost": 8552.06
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 2",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 1.85,
            "num_diff": 15,
            "ducting_lbs": 600,
            "duct_insulation_ft2": 375,
            "flex_duct_sz_in": 12,
            "flex_duct_length_ft": 150,
            "cost": 8552.06
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 3",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.891,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 3",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.891,
            "num_diff": 8,
            "ducting_lbs": 795,
            "duct_insulation_ft2": 528,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 64,
            "cost": 7921.95
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 4",
            "ducting_direction": "Supply",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.593,
            "num_diff": 6,
            "ducting_lbs": 495,
            "duct_insulation_ft2": 380,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 48,
            "cost": 5283.63
          },
          {
            "ThermalZone": "ALL_ST=Office open plan_FL=Building Story 3_SCH=A 4",
            "ducting_direction": "Return",
            "tz_mult": 1.0,
            "airflow_m3ps": 0.593,
            "num_diff": 6,
            "ducting_lbs": 495,
            "duct_insulation_ft2": 380,
            "flex_duct_sz_in": 10,
            "flex_duct_length_ft": 48,
            "cost": 5283.63
          }
        ]
      }
    ]
  ],
  "pl_comments": "This could be in the air_loops table?",
  "hrv_return_ducting": [
    {
      "floor": "Building Story 1",
      "air_systems": [
      ]
    },
    {
      "floor": "Building Story 2",
      "air_systems": [
      ]
    },
    {
      "floor": "Building Story 3",
      "air_systems": [
      ]
    }
  ],
  "hrv_total_cost": 21049.02559211311
}
```

**Comment by jblake59** [comment] 2019-10-31 19:55
My reply to @phylroy comments above:

**"pl_comment: Why not just append this information to an airloop table?"**
--> Done.

**"pl_comment: is there always only one hrv in an airloop? If so, promote this information up. ",**
--> Yes, just one hrv per airloop. Hash promoted.

**"pl_comment: It may be a good idea to create a coils table with the coil information.. ",**
--> Done.

**"pl_comment: It may be a good idea to create a terminal vav table.. ",**
-->Done.

**"pl_comment: mech_to_roof question/suggestion.. ",**
-->These distances are for gas, HW and Electrical conduits that run from the building mechanical room to the roof. This does not include zone level gas, HW or electrical conduits. They've been added to the building level of btap_data

**"pl_comment: "Could we have all the ductwork in the same table.. ",**
-->Yes we can combine trunk ducts with floor trunk ducts. Note that ductwork and piping for zone terminal systems are in the heating and cooling section labelled "h&c_plant_zonal_systems_cost_table". The NumberRuns value depends on the system types in the building and is either 1 or 2.

**"pl_comment: "tz_distribution: This could be in the thermal zone table with the building story as a column in that table.. ",**
--> Need to check with @ckirney to make sure that return ductwork data is always a duplicate of supply data . There are also a lot of empty arrays in this table that I believe have data in certain circumstances.

**"pl_comment: "hrv_return_ducting: Could this be put into the air_loops table?.. ",**

**Closed** 2020-06-16 17:15 UTC
Labels: Costing, Priority High
