### ISSUE TITLE
NECB 2011/15: SHW is hardcoded by building type. 

### ISSUE THREAD

**Issue by phylroy** [canmet-energy/btap_tasks#46] opened 2018-05-04 16:26 UTC
The way the NECB 2011 creates the SHW loop is hardcoded to set tank volume, and capacity in the JSON file here. 
https://github.com/NREL/openstudio-standards/blob/nrcan/lib/openstudio-standards/standards/necb/necb_2011/data/prototype_inputs.json#L8495

This needs to be generalized to use NECB standard schedules and autosized based on expected SHW load.  It also needs to be in line with the fuel type set by the region.  So this method...

https://github.com/NREL/openstudio-standards/blob/nrcan/lib/openstudio-standards/standards/necb/necb_2011/service_water_heating.rb#L2

...needs to be re-written to be not dependent on the prototype_input.json data. 

This may require a complete re-write of the SHW logic to be more general. 

Perhaps the routine that Andrew wrote for A90.1 could be of use here. 
https://github.com/NREL/openstudio-standards/blob/nrcan/lib/openstudio-standards/standards/Standards.Model.rb#L98

**_Note_**: Issue #12 has been closed and merged into this issue (see below).

**Comment by jblake59** [comment] 2018-06-07 18:43
**Merged in Issue #12** (that has been closed)
Spec writer: Mike
Implementation in BTAP: Jeff
Tester: Mike

Table 6.2.2.1 contains information on efficiencies of service hot-water equipment. The current implementation of the NECB 2011 rules for SHW makes use of several assumptions used in the compliance rules of ASHRAE 90.1. During this task, a document describing the current implementation of the SHW compliance rules will be reviewed. The method will then be updated for NECB 2015 based on the information in Table 6.2.2.1.

Quality assurance tasks:
New unit test for SWH
All unit tests pass
All regression tests pass

**Comment by ckirney** [comment] 2018-08-13 16:55
Made major revisions to model_add_swh method in service_water_heating.rb.  I also added the auto_size_shw_capacity, and auto_size_shw_pump_head methods.

The auto_size_shw_capacity method does the following:
-Finds all the spaces in a model;
-Determines the shw flow rate for each space from the appropriate spacetypes.json data file;
-Determines the schedule for each space from the appropriate spacetyes.json data file;
-From the above two determine the total flow rate for all of the spaces in the building for each hour of the three design days (Weekday/Default, Saturday and Sunday/Holiday);
-Determine which hour has the highest total flow rate (this becomes the peak hour) and the total flow rate for the next hour;
-If there are multiple peak hours with the same flow rate, of those hours determine which has the highest flow rate the hour after (this becomes the peak hour);
-Set the tank volume to the total shw draw for the peak hour;
-Assume all of the hot water is drawn in the first part of this hour;
-Determine how long this draw is by dividing the total shw draw for the peak hour by the total maximum shw draw for all the spaces (i.e. the sum of the peak flows for each space regardless of draw schedule)
-Determine the recovery time by assuming that the tank must heat the tank volume in the remainder of the hour;
-If the tank has a recovery time of 0.2 hrs or less set the tank volume to that required to satisfy the peak hour and the hour after and set the recovery time to 1 hour;
-Set the capacity to be the power required to heat the entire tank volume in the recovery time.

The auto_size_shw_pump_head method does the following:
-Sums the peak flow rate for each space in the building to determine the total peak flow rate (like in auto_size_shw_capacity without the scheduling considerations);
-determine which conditioned spaces are in the lowest level of the building (have the lowest floor z-values)
-Of these spaces, determine which is closest to the building centroid and assume that the shw tank is in the middle of that space (regardless of what the space is so you could have a shw tank in a lobby, corridor, office space, or other ridiculous place)
-Determine the vector between the centroid of the shw tank space floor and the floors of each space with a shw demand;
-Sum the x, y, and z coordinates of the vectors determined in the previous step and find which is longest, this becomes the length of the longest pipe;
-Assume the shw pump has to push the total peak flow rate for the entire building through the longest pipe;
-Determine the friction factor for the pipe (this from the friction_factor method)
-The pump head becomes the pressure required to push the total peak flow rate for the entire building through twice the longest pipe distance.

Note that auto_size_shw_pump_head makes assumptions for pipe diameter, pipe roughness, viscosity of fluid (water), and density of fluid (water).  These assumptions are expressed as default arguments for the method.  You can change these defaults by changing the arguments passed to the method.  However, the method is only valid for newtonian fluids.  Also note that the viscosity of water is really sensitive in the typical shw range.  I assumed the temperature of the water was at 60 C.  While you cannot change this assumption directly, you can change the density and viscosity assumptions to reflect those for whatever newtonian fluid at whatever temperature.

The friction_factor method determines the Darcy-Weisbach friction factor (no weird chem-eng friction factors here!!!).  For RE <= 2100 I use the Uagen-Poiseuille equation, for RE > 4000 I use Serghide's equation, for RE between 2100 and 4000 I use linear interpolation (which everyone says you cannot do but I do it anyway because no one has a better alternative).

With the tank sized and the pump sized the shw plant loop and tank are made using the model_add_swh_loop (I didn't change anything here).  If you have a weird building with no swh demand then a plant loop is still made with a tank of 0 volume and 0 capacity.  The pump head is set to the OpenStudio 2.4.1 default in this case (which is really high for a building with no shw).  If you have a shw demand the end uses are then added using the model_add_swh_end_uses_by_spaceonly method.  This is essentially the same as the model_add_swh_end_uses_by_space method that already existed but without the need for building_type and climate zone.

**Comment by ckirney** [comment] 2018-08-13 18:07
Changes and test merged into nrcan branch 2018-08-13 in commit b5ce493cd67c6ff8a1da53630cdaad9b3b7549e0.

**Closed by ckirney** 2018-08-13 18:07 UTC
Labels: In Progress, NECB 2011, NECB 2015, Priority High, Standards

**Comment by ckirney** [comment] 2018-08-15 17:31
Compared results to autosize results from EnergyPlus.  Method:
-Modified auto_size_shw_capacity method so that recovery time cut-off (to switch to sizing the tank as
serving the peak hour and the next hour) to 0.1 hours (this kept sizing to the current hour, avoiding complications for the E+ test). 
-Used BTAP NECB2015 Outpatient regression test and NECB2011 Primary School regression test, both in Calcary, to generate osm file.
-Ran in debug mode so could retrieve recovery time that auto_size_shw_capacity method calculates and peak flow.
-Ran osm in OpenStudio to generate idf file.
-Modified idf file as follows:
--created a sizing object with peak flow as sizing method, recovery time as whatever was calculated above, and the time the tank had to serve as 1 hour.
-Ran modified idf in Eplus
-Opened .sql file to get autosized volume, flow rate and capacity.

Eplus ended up calculating volume as the tank flow rate multiplied the time the tank served for.  The tank flow rate was the sum of the flow rates for each space in the building.  The auto_size_shw_capacity method sets the time the tank has to serve somewhat differently (see notes above).  However, the way that BTAP autosizes the tank is consistent with consistent with how Eplus does.

The maximum heating capacity that Eplus calculated was somewhat different than how BTAP does.  For the two tests the difference between the what Eplus calculated and how BTAP would calculate (with same tank volumes, and changing density of water to 983 kg/m^3 rather than 1000 kg/m^3) was consistently 1.043056 (BTAP capacity 1.043056 times higher than Eplus capacity).  I am fairly sure that this difference is a result of some differences in the Cp, density and, more importantly, assumed temperature difference (BTAP assumed 60 C - 15 C = 45 C, I back-calculated E+ as 43.1425).  However, as with volume the ways that BTAP and E+ calculate capacity are consistent.
